---
output:
  html_document: default
  word_document: default
  pdf_document: default
---
# Alewife (*Alosa pseudoharengus*)

This chapter is dedicated to the exploration of the habitat preferences and life cycle of alewives (*Alosa pseudoharengus*) in the northeastern United States. Despite their historical significance, alewife populations have encountered significant declines, leading to their classification as a "species of concern" by the U.S. National Marine Fisheries Service [@nmfs_national_marine_fisheries_service_species_2009]. Various factors contribute to this decline, including deteriorating water quality, habitat loss, offshore bycatch/overfishing, increased predation, and dam construction [@kocovsky_linking_2008; @nmfs_national_marine_fisheries_service_species_2009; @bethoney_environmental_2014; @waldman_north_2022]. The consideration for inclusion in the U.S. Endangered Species List has also been raised, as indicated in reports by the National Marine Fisheries Service in 2013 [@nmfs_national_marine_fisheries_service_endangered_2013].

Recent stock assessments reveal diverse trends in documented alewife runs over the last ten years, with some populations showing signs of stabilization or even growth [@asmfc_river_2017]. In 2019, the National Marine Fisheries Service concluded that listing the alewife as threatened or endangered under the Endangered Species Act (ESA) was not warranted [@nmfs_national_marine_fisheries_service_not_2019].

Alewives are widely distributed throughout the northeastern United States, thriving in freshwater rivers and estuaries along the Atlantic coast [@asmfc_fishery_1985]. While historically known for extensive migrations to spawn in freshwater tidal systems, limited information is available about estuary movements for alewives. This chapter aims to explore the favorable habitat conditions for spawning alewife adults, non-migratory juveniles, as well as eggs and larvae, considering factors such as temperature, depth, salinity, flow velocity, and substrate.

## Life cycle overview

Alewives have a complex life cycle with distinct stages and behaviors. Spawning occurs in waves during spring, triggered by rising water temperatures and increasing day length [@asmfc_amendment_2009; @mccartin_new_2019; @able_alewife_2020]. Adult alewives migrate upstream from marine environments to suitable brackish or freshwater spawning habitats [@pardue_habitat_1983; @bigelow_bigelow_2002]. Recent observations also suggest a correlation between alewife migration and the lunar phase [@legett_daily_2021].

Alewife migration and spawning precedes blueback herring by 2-3 weeks [@fay_alewifeblueback_1983]. Alewives exhibit a north-south seasonal migration pattern, with migrating adults potentially detouring into estuaries (Greene et al., 2009). Upon arrival at the spawning grounds, adult alewives engage in immense spawning runs, where large groups gather to deposit their adhesive eggs over a variety of substrates [@oconnell_spawning_1997; @able_alewife_2020]. After spawning, both males and females return to the marine environment.

In the spawning habitat, the incubation period for eggs lasts 3-6 days [@munroe_overview_2000; @bigelow_bigelow_2002]. The eggs hatch into yolk-sac larvae, representing an early developmental stage where larvae rely on an attached yolk sac for nutrients before transitioning to external feeding. For alewives, this stage typically lasts 2-5 days _(Bourne 1990)._

After this stage, larvae remain in the estuary to grow and migrate downstream towards more brackish areas, maturing into juvenile fish [@pardue_habitat_1983]. These brackish areas serve as nurseries until the juvenile alewives migrate to the sea [@laney_relationship_1997; @kosa_processes_2001]. Alewife larvae can adapt to high salinities (35 psu) by 50 days post-hatch _(DiMaggio et al. 2015)._ However, the survival rate for larvae is relatively low, with only a small percentage successfully reaching the sea, potentially as low as 1%, depending on ecosystem conditions [@kissil_spawning_1974]. Similarly, mortality rates for migratory adults during a spawning season can reach as high as 90% [@brady_part_2005].

## Habitat Requirements

### Spawning Adult Alewives

Spawning adult alewives exhibit specific habitat preferences and requirements. Their annual migration during spawning is energetically demanding, with notable variations in behavior. Some studies suggest fasting during the day and extensive feeding at night, while others report refraining from eating until their return downstream to productive tidal habitats [@janssen_feeding_1980; @bigelow_bigelow_2002, (Greene et al., 2009)].

Preferred spawning habitats include lacustrine and fluvial environments rather than riverine ones [@reback_survey_2004; @frank_role_2011]. Alewives spawn and rear in upper river pools _(Turner & Limburg 2016) (Greene et al., 2009)._

#### Temperature

Spawning adult alewives exhibit distinct temperature preferences crucial to their reproductive success and migration patterns. The spawning process commences at temperatures around 10.5 °C, with upstream migration initiating within the range of 5°C to 10°C [(Cianci 1969); (Mullen et al., 1986); (Loesch 1987); @munroe_overview_2000; (Reback et al., 2004)]. Notably, limited instream movement is observed below 8°C or over 18°C, emphasizing the species' preference for moderate temperature conditions [(Durbin et al., 1979); Collette and KleinMacPhee 2002]. Spawning ceases at temperatures exceeding 27°C, indicating an upper limit for optimal reproductive activity [(Kissil 1974);@pardue_habitat_1983; @brown_habitat_2000; (Reback et al., 2004)]. The optimal temperature range for successful spawning is broadly identified as 10°C to 22°C, with consensus suggesting peak spawning occurring within the narrower range of 12 to 16 degrees Celsius [Tyus 1974; Pardue 1983; (O’Connell & Angermeier, 1997); Collette and Klein-MacPhee 2002]. While deviations from the optimal temperature range can impact spawning success and migration timing, the overall picture indicates that alewives thrive in moderate temperature conditions.

#### Depth

Spawning adult alewives exhibit specific depth preferences during their reproductive activities. Notably, adult alewives migrating inland show an overall preference for depths below 100 meters [@pardue_habitat_1983; @munroe_overview_2000]. Species of herring from the same clupeid family have been known to spawn at depths ranging from 0.5 to 15 meters (Haegele & Schweigert 1985). Alewives generally favor depths from Mean Low Tide (MLT) to 10 meters [@brown_habitat_2000]. Other studies report that alewives favor more shallow spawning habitats ranging from 0.15 to 3 meters [@pardue_habitat_1983] _(Greene et al., 2009)_, with significant spawning recorded around 0.5 meters (Kosa & Mather 2001). Additional field observations, reveal a significant proportion of alewives occupying habitats as shallow as 2 meters [@mather_assessing_2012], with the majority of spawning occuring at less than 1 m (Murdy et al. 1997). This variability in depth preferences reflects the adaptability of alewives to different environmental conditions during their spawning and migration phases.

#### Salinity

The documented behavior of alewives challenges conventional beliefs about anadromous species exclusively relying on freshwater environments for spawning. Observations reveal that alewives engage in spawning activities in freshwater tidal habitats with minimal salinity concentrations, demonstrating adaptability to environments with salinity levels below 0.5 psu [@pardue_habitat_1983; @brown_habitat_2000]. This adaptability extends to tolerating higher salinity levels, with successful spawning observed in concentraions of 8 psu [@able_alewife_2020]. Other research by @brown_habitat_2000 emphasizes a heightened preference for habitats with salinity concentrations below 15 psu, deeming concentrations exceeding 20 psu unsuitable for spawning adults. 

Field studies further document that adult alewives exhibit spawning activities across diverse estuary habitats with varying salinity levels, including coastal ponds, pond-like regions in coastal rivers and streams, oxbows, eddies, backwaters, stream pools, and flooded swamps [@pardue_habitat_1983; @mullen_species_1986; @collette_fishes_2003; @walsh_early_2005]. Remarkably, species of herring from the same clupeid family have been known to spawn in a wide range of salinities, from freshwater to levels exceeding 35 psu (Haegele & Schweigert 1985). This adaptability underscores the versatility of alewives in utilizing estuarine habitats with varying salinity conditions for their spawning activities.

#### Flow Velocity

The flow velocity preferences for adult alewives are crucial for understanding spawning habitat [@tommasi_effect_2015]. @haro_swimming_2004 highlighted the challenges faced by smaller species, including alewives, when subjected to high velocities above 3.5 m/s, leading to impingement issues and poor performance. In contrast, lower velocities, particularly below 1.7 m/s, as observed by @walsh_early_2005, are favored by alewives. @mather_assessing_2012 found that tagged alewives spent minimal time in riffle–run habitats but preferred pools, with varying locations of pool occupancy. 

While conventional wisdom suggests that alewives spawn in slow-moving habitats with little to no current, @haro_swimming_2004 swimming experiments also revealed that migratory alewives can travel farther distances upstream when flow velocities are increased to 1.5 m/s, compared to 3.5 m/s. However, these experiments indicated very little suitability for upstream migration when velocities reach above 3.5 m/s, suggesting no suitability if tested at 4.5 m/s [@haro_swimming_2004]. Older findings identify velocities up to 0.3 m/s as suitable for spawning [@pardue_habitat_1983]. Understanding the influence of flow velocity is key for effective management and preservation of the habitat conditions required for successful alewife spawning.

#### Substrate

Previous studies have presented conflicting information regarding the substrate preferences of spawning adult alewives, often stemming from the generalization of alewives with blueback herring as river herring. Despite @brown_habitat_2000 arguing that substrate composition holds no significance in alewife models, contrasting observations from various sources, including studies by @fay_alewifeblueback_1983, @killgore_distribution_1988, @oconnell_spawning_1997, and @able_alewife_2020, present compelling evidence of a more defined range of substrate preferences. These preferences span a variety of unconsolidated substrates, such as small gravel, sand, detritus, and other soft substrates, as documented by @pardue_habitat_1983, _bourne 1990_, @oconnell_spawning_1997, @brown_habitat_2000, and (Greene et al., 2009). Moreover, there is an indication that spawning adult alewives may avoid habitats containing sub-aquatic vegetation (SAV), according to findings by @killgore_distribution_1988 and @laney_relationship_1997. Comprehending and defining these substrate preferences is crucial for effectively managing and conserving the appropriate spawning habitats for alewives.

### Non-Migratory Juveniles

Non-migratory juvenile alewives have distinct habitat preferences and requirements, which significantly differ from those of spawning adult alewives. Various factors, including temperature, depth, salinity, flow velocity, and substrate, impact the abundance and successful development of young alewives, as evidenced in studies conducted by @pardue_habitat_1983, @walsh_early_2005, and @tommasi_effect_2015. A comprehensive understanding of the preferred habitats for juvenile alewives is essential for meeting their ecological needs.

#### Temperature

Temperature plays a pivotal role in shaping the distribution, behavior, and early development of non-migratory juvenile alewives [@tommasi_effect_2015]. Specific river observations, including the Delaware River at 22°C, Potomac River at 22.3°C, and Nanticoke River at 21.8°C, identify critical temperature thresholds associated with peak juvenile recruitment [@tommasi_effect_2015]. The optimal temperature for nursery rearing is found to be 20–23°C [@tommasi_effect_2015], with a maximum preference for young alewives estimated at 26.3°C (Kellogg, 1982). Supporting these findings, observations in the Eel River showed a mean temperature of 23.1°C, while the Herring River (Bourne) exhibited a mean temperature of 25.1°C (Ames & Lichter, 2013).

The broader suitability range for juvenile recruitment spans 11°C to 28°C (@pardue_habitat_1983; Fay, 1983; Klauda, 1991; Brown, 2000; Munroe, 2000; @tommasi_effect_2015). Juvenile alewives do not survive temperatures below 3°C (Otto, 1976; Kellogg, 1982; @pardue_habitat_1983; Mullen et al., 1986). Specific thresholds, such as feeding behavior disruption at 6.7°C and schooling behavior disruption at 4.5°C, underscore the vulnerability of juvenile alewives to temperature fluctuations, with complete disorientation occurring at 2.8°C (Mullen et al., 1986). Exposure to temperature extremes outside the suitable range can negatively impact juvenile growth and performance (Pörtner and Farrell, 2008; Kellogg, 1982; Henderson and Brown, 1985; Overton et al., 2012). Maintaining temperatures within the suitable thresholds is crucial for ensuring successful development and overall health of non-migratory juvenile alewives.

#### Depth

The depth preferences of non-migratory juvenile alewives, as observed in studies such as Brown et al. (2000) and Mullen et al. (1986), differ significantly from their adult counterparts. Juveniles exhibit a preference for depths ranging from 0 to 10 meters, and no observed habitat suitability beyond 20 meters [@brown_habitat_2000; @hook_annual_2008]. Additional research by Pardue (1983) reinforces this trend, indicating that juveniles favor depths between 0.5 to 5 meters, and their abundance notably increases around five-meter depths [@pardue_habitat_1983]. Similarly, other juvenile clupids were found abundant in 4.6 meters (Mullen et al., 1986). After leaving the estuary, juveniles can be found in deeper waters off-shore before swimming farther out to sea (Greene et al., 2009). These combined field observations show that the optimal depth for juvenile alewives is equal to or less than 5 meters.

#### Salinity

Juvenile alewives display considerable adaptability to varying salinity levels, as evidenced by physiological changes observed in response to seawater exposure. This adaptation suggests capacity for osmoregulation, enabling them to regulate salt and water balance and maintain stability in seawater environments (Christensen et al., 2012). Additional studies, such as Leim (1924), Pardue (1983), and Brown et al. (2000), provide further insights into the versatility of alewives in diverse salinity conditions and imply that alewives can thrive in environments with fluctuating salinity, showcasing adaptability to both freshwater and saltwater habitats during different life stages.

Research by Richkus (1974) indicates that juvenile alewives, transferred between freshwater and saline water, experienced zero mortality, suggesting a robust tolerance to salinity changes. However, DiMaggio et al. (2015) note lower survival rates when transferred from higher salinities to lower ones, emphasizing a potential preference for higher salinity environments. The presence of juvenile alewives in estuarine waters, where they are preyed upon by bluefish (Creaser and Perkins, 1994), underscores their distinct salinity preference, spanning from areas exceeding 10 psu to levels as high as 30 psu (@pardue_habitat_1983; @brown_habitat_2000). Turner et al. (2016) and Able (2020) highlight juvenile preference for estuarine habitats with salinity concentrations ranging from 0.5 to 25 psu, promoting an ideal balance between freshwater and marine conditions for growth. Overall, juvenile alewives exhibit a versatile salinity preference, showcasing their adaptability to diverse environments for optimal growth and survival.

#### Flow Velocity

Flow velocity preferences play a pivotal role in the development and survival of non-migratory juvenile alewives. Laboratory experiments suggest that juvenile alewives tend to avoid water velocities exceeding 0.1 m/s, particularly in narrow channels (Gordon et al., 1992). Further research by Richkus (1975) and O'Connell (1999) documents the preference of juvenile alewives for habitats with flow velocities ranging from 0.05 to 0.17 m/s [@richkus_response_1975; @oconnell_habitat_1999]. Slower flow rates are conducive to energy conservation and effective foraging, while higher flow velocities may impede access to critical food resources, and disrupt their position in the water column [@haro_swimming_2004; @able_alewife_2020]. Understanding these flow velocity preferences is essential for informed habitat management, ensuring successful transitions for non-migratory juvenile alewives from egg to adulthood.

#### Substrate

Non-migratory juvenile alewives have broad substrate preferences, underscoring their adaptability to diverse aquatic environments. While earlier studies, such as @fay_alewifeblueback_1983, indicated a preference for sandy substrates, recent observations suggest a potential inclination towards rocky substrates [@janssen_preference_2004; (Kornis & Janssen, 2011); @boscarino_influence_2020]. Alewife catches at rocky sites have been reported to be much higher than those at sandy sites, possibly attributed to the increased profitability of rocky habitats for feeding on zooplankton [@janssen_preference_2004];(Kornis & Janssen, 2011); (Wells, 1980). These substrate preferences have implications for habitat management, as understanding the varied substrate choices of juvenile alewives is crucial for creating environments conducive to their successful development and survival.

The presence of seagrass and submerged aquatic vegetation (SAV) is important to non-migratory juvenile alewife habitat. Despite some studies suggesting avoidance of areas with aquatic vegetation [@ingel_habitat_2013], research by @laney_relationship_1997, Olney and Boehlert (1988), (Greene et al., 2009), and @smith_overlapping_2015 contradict this, emphasizing that seagrass beds provide essential nursery habitats for juvenile alewives. These vegetated areas serve as refuge from predators and offer abundant food sources. Seagrass beds also contribute to enhanced water quality by stabilizing sediments and promoting nutrient cycling, creating an optimal environment for the thriving of juvenile alewives. The significance of SAV extends to overwintering habitats, as suggested by @killgore_distribution_1988. The understanding of these diverse substrate preferences and the crucial role of seagrass coverage is pivotal for effective habitat management, ensuring the successful development of non-migratory juvenile alewives in varied aquatic environments.

### Eggs & Larvae

The early life stages of alewives, particularly their planktonic larval phases, are characterized by vulnerability to passive transport dispersal (Schmidt et al., 1988). Understanding the habitat preferences exhibited by alewife eggs and larvae is essential for comprehending their developmental dynamics and ensuring optimal conditions for survival. This section will delve into key environmental parameters influencing the distribution and behavior of alewife eggs and larvae. Factors such as temperature, depth, salinity, flow velocity, and substrate play crucial roles in shaping the habitat preferences of these early life stages. Notably, studies, such as those by O'Connell and Angermeier (1997), emphasize the significant influence of current velocity as one of the strongest predictors for the presence of alewife eggs. 

#### Temperature

Water temperature significantly shapes the growth, survival, and overall development of alewife eggs and larvae. Pardue (1983) and Kellogg (1982) studies reveal the optimal temperature for larval growth at approximately 26.4°C, with the estimated peak at 26.3°C. A broad suitable temperature range is evident as egg survival occurs between 12°C and 30°C, and temperatures exceeding 31°C lead to larvae mortality (Kellogg, 1982). Beyond direct developmental impacts, temperature influences the suitability of nursery areas, as noted by Tommasi (2015). Specific river systems, like the Chowan River, experience temperatures surpassing the upper thermal tolerance of alewife larvae, influencing their distribution (Kellogg, 1982).

The association between peak densities of alewife larvae and water temperature peaks underscores the temperature sensitivity of early life stages (O'Connell & Angermeier, 1999). Lower temperatures and peaks in river flow negatively affect alewife larvae, indicating a complex interplay between temperature and environmental conditions (O'Connell & Angermeier, 1999). Optimal temperature ranges for egg density peaks fall between 16-21°C and 11-28°C, showcasing the adaptability of alewife eggs to varying temperature conditions (O'Connell & Angermeier, 1999; Klauda et al., 1991). This is supported in observations from (Kellogg, 1982) where maximum hatching success occurred at 12.7°C, 15.0°C, and 20.8°C. Optimal hatching temperature is defined at 16°C (Edsall, 1970), with hatching success ceasing above 29.7°C (Kellogg, 1982; Pardue, 1983). These findings collectively emphasize the role of water temperature in the early life stages of alewives.

#### Depth

Alewife eggs and larvae exhibit clear depth preferences, primarily favoring shallow-water habitats during their early life stages. Observations from Lake Ontario, as documented by Klumb et al. (2003) and Ingel (2013), reveal that alewife larvae are uniformly distributed in nearshore areas, with a significant presence in waters less than 5 meters deep. In the same lake, early post-hatch larvae are particularly abundant in depths less than 3 meters, while larger larvae progressively inhabit deeper habitats (Ingel, 2013; Dunstall, 1984). Studies conducted in Nova Scotia's Margaree River and other locations further emphasize this trend, indicating that alewife larvae predominantly reside in depths shallower than 2 meters (Mullen et al., 1986; Pardue, 1983). The preference for shallow-water habitats is linked to the benefits these environments offer, providing protection from predators and facilitating access to essential food sources, crucial for the growth and development of alewife larvae into juveniles. 

#### Salinity

While there are observations indicating that alewives utilize freshwater streams for their early life stages (Kosa and Mather, 2001; Tommasi, 2015), Mullen et al. (1986) provide evidence of their high tolerance to salinity changes. Pardue's study (1983) reports the presence of alewife eggs and larvae in environments with salinity levels below 12 ppt, suggesting a potential inclination towards slightly saline conditions. This inclination is corroborated by Dovel (1971), who notes that the growth rates of alewife larvae are significantly lower in freshwater compared to slightly saline water, ranging from 1.0 to 1.3 ppt. The adaptability of alewives to a range of salinities is evident in their ability to thrive in different conditions.

Similarly, other clupeid eggs display tolerance to salinities in the range of 3-33%, and herring eggs and larvae are reported to develop abundantly in seawater with healthy and active larvae (Haegele & Schweigert, 1985; Ford, 1929). DiMaggio et al. (2015) offer valuable insights into the survival rates of alewives at different salinities, with the highest mean survival rate observed at 15‰ salinity (76.0%). As salinity increases to 20‰ and 30‰, the mean survival rates for alewives decrease to 69.3% and 64.7%, respectively. This pattern suggests a potential preference for moderate salinity conditions, supported by the higher survival rates at 15‰ compared to higher salinities. DiMaggio's study (2015) further highlights the adaptability of alewife embryos, showing survival rates above 97% at low salinities (2, 5, and 10 g/L) and decreased survival at salinities above 15 g/L. Overall, these findings highlight the broad salinity preferences that promote successful early development and survival of alewife eggs and larvae.

#### Flow Velocity

The early egg stages of alewives exhibit a positive relationship with flow velocity, particularly in the range of 0.03-0.2 m/s (O’Connell & Angermeier, 1999). However, there is a rapid decline in larvae abundance associated with high flows, suggesting that extreme water velocities can be detrimental to their survival (O’Connell & Angermeier, 1999). Insights from the Delaware River indicate that excessively high flows may negatively impact alewife recruitment, as elevated water velocity can create barriers that hinder the swimming performance of anadromous fish (Haro et al., 2004).

In specific habitats, larval alewives tend to be consistently found in water velocities up to 0.12 m/sec, avoiding faster currents (Ingel, 2013). The distribution of alewife larvae is not primarily influenced by overall tidal fluctuations or the highest speeds of water flow; rather, it is influenced by more localized and instantaneous changes in velocity (Ingel, 2013). Previous studies, such as Pardue (1983), observed optimal velocities for larvae and egg development ranging from 0 to 0.3 m/s. These findings collectively highlight the importance of flow velocity in shaping the distribution and development of alewife eggs and larvae, emphasizing the significance of suitable flow conditions for their early life stages.

#### Substrate

Substrate preferences significantly influence the distribution and habitat selection of alewife eggs and larvae. The sandy substrate on the eastern side of Lake Michigan was identified as a favorable environment for the primary and secondary production, limiting dreissenid mussel biomass and providing better support for prey available to larval alewife (Prendergast, 2019). Detritus concentrations, a key variable associated with larval growth rate, are positively correlated with productive regions in Lake Michigan, indicating increased prey availability for larval alewife in areas with high detritus concentrations (Prendergast, 2019). Pardue (1983) also suggests that optimal egg and larval habitat is found in substrates composed of 75% silt or other soft material containing detritus and vegetation. Soft substrates, such as sand, are considered conducive to the successful development of alewife eggs and larvae. Further, larvae have not been commonly reported in abundance over hard substrates. Reports of eggs on hard substrates might be attributed to the temporary adhesive property of alewife eggs rather than a preference for hard substrate habitats. 

Although SAV is thought to provide spawning and nursery habitat for most anadromous and resident fishes, alewife larval catch is inversely related to SAV density, with larvae most frequently found in areas with less than 10 percent vegetation density and never in areas exceeding 30 percent vegetation density (Miller et al 2006); (Ingel, 2013). Studies by Anderson and Schmidt (1989) and Schmidt and Kiviat (1988) further highlights the impact of vegetation cover, like water-chestnut and water celery beds, on the distribution of larval alewife, with a decline in larval abundance following the establishment of dense water-chestnut cover. These findings collectively highlight the substrate preferences of alewife eggs and larvae, emphasizing the importance of soft substrates and vegetation coverage in their habitat.

## Habitat suitability models

Existing alewife habitat suitability models, originally developed by @brown_habitat_2000 and @pardue_habitat_1983, with reliance on similar sources such as @bigelow_fishes_1953 and the updated version (Bigelow et al., 2002), possess several limitations that make them inadequate for current applications.
Primarily, these models are constructed solely on observations of alewives' daytime behavior, neglecting their significant nocturnal activity patterns.
Recent studies have revealed that alewives are substantially active at night, engaging in feeding and exhibiting substantial downstream movement during these nocturnal periods [@janssen_will_1978; @janssen_feeding_1980; (Greene et al., 2009); @mccartin_new_2019].
@collette_fishes_2003 and (Greene et al., 2009) even note that groups of alewives spawn in the evening.
Consequently, the primary focus on daytime behavior in the existing models fails to capture the true habitat preferences and requirements of alewives, particularly in estuary and brackish environments.

Furthermore, the current models predominantly consider variables such as temperature, depth, and substrate, while disregarding other crucial factors that significantly influence alewives' habitat selection, including flow velocity, sub-aquatic vegetation, and life stage differences.
This limited scope results in incomplete assessments of habitat suitability.
Moreover, the existing models fall short of encompassing the comprehensive spectrum of knowledge available for alewives, as inconsistencies and potential inaccuracies emerge from conflicting information concerning substrate, salinity, and depth preferences.
These limitations undermine the models' effectiveness in predicting habitat suitability for alewives, and since the release of these models, updated observations and stock assessments have been published that offer more detailed information on the habitat for alewives.

To address these shortcomings, habitat models should encompass a more comprehensive understanding of alewives' behavior, specifically acknowledging their use of estuarine and brackish habitats.
These habitats serve as critical areas for alewives, exhibiting relatively high levels of habitat use [(Greene et al., 2009); @mccartin_new_2019; @stevens_evidence_2021].
Incorporating these estuarine and brackish areas into management strategies is of paramount importance to ensure the conservation and successful management of the species.
Notably, utilizing estuaries and brackish habitats for spawning may offer energetically favorable conditions for alewives, as it eliminates the need for them to acclimate to complete freshwater environments [@dimaggio_spawning_2015].
This recognition highlights the significance of incorporating these habitats into conservation efforts and management plans to safeguard the species and support their reproductive success. The objective of this section is to define an updated habitat model for the spawning adult, non-migratory juvenile, and egg and larvae life stages of the alewife. 

### Spawning Adult Alewives

The updated HSI model for spawning adult alewives introduces several noteworthy breakpoints that distinguish it from previous models.
These breakpoints provide a more refined understanding of alewife habitat preferences and suitability.

+----------------------------+--------------------+-------------------------------+
| **Parameter**              | Range              | **Habitat Suitability Value** |
+============================+====================+===============================+
| A. Temperature (°C)        | $0 < t < 8$        | 0.0                           |
|                            |                    |                               |
|                            | $8 <= t < 12$      | 0.5                           |
|                            |                    |                               |
|                            | $12 <= t < 16$     | 1.0                           |
|                            |                    |                               |
|                            | $16 <= t < 22$     | 1.0                           |
|                            |                    |                               |
|                            | $22 <= t < 27$     | 0.5                           |
|                            |                    |                               |
|                            | $27 <= t < 30$     | 0.1                           |
|                            |                    |                               |
|                            | $t > 30$           | 0.0                           |
+----------------------------+--------------------+-------------------------------+
| B. Depth (*meters*)        | $MLT < d < 2$      | 0.0                           |
|                            |                    |                               |
|                            | $2 <= d < 10$      | 0.5                           |
|                            |                    |                               |
|                            | $10 <= d < 20$     | 1.0                           |
|                            |                    |                               |
|                            | $20 <= d < 50$     | 0.5                           |
|                            |                    |                               |
|                            | $50 <= d < 100$    | 0.5                           |
|                            |                    |                               |
|                            | $d > 100$          | 0.5                           |
+----------------------------+--------------------+-------------------------------+
| C. Salinity (*psu*)        | $0 < s < 0.5$      | 1.0                           |
|                            |                    |                               |
|                            | $0.5 <= s < 5.0$   | 1.0                           |
|                            |                    |                               |
|                            | $5.0 <= s < 15.0$  | 1.0                           |
|                            |                    |                               |
|                            | $15.0 <= s < 20.0$ | 0.5                           |
|                            |                    |                               |
|                            | $s > 20$           | 0.0                           |
+----------------------------+--------------------+-------------------------------+
| D. Flow Velocity (*m/s*)   | $0 < v < 0.3$      | 1.0                           |
|                            |                    |                               |
|                            | $0.3 <= v < 1.5$   | 1.0                           |
|                            |                    |                               |
|                            | $1.5 <= v < 3.5$   | 0.5                           |
|                            |                    |                               |
|                            | $3.5 <= v < 4.5$   | 0.3                           |
|                            |                    |                               |
|                            | $4.5 <= v < 5$     | 0.1                           |
|                            |                    |                               |
|                            | $v > 5$            | 0.0                           |
+----------------------------+--------------------+-------------------------------+
| E. Substrate               | Hard Substrate     | 0.5                           |
|                            |                    |                               |
|                            | Soft Substrate     | 1.0                           |
|                            |                    |                               |
|                            | Present SAV        | 1.0                           |
|                            |                    |                               |
|                            | Absent SAV         | 0.5                           |
+----------------------------+--------------------+-------------------------------+
**Table 1.** Model Parameters and Habitat Suitability Values for Spawning Adult Alewives

#### Temperature

- Alewives begin spawning at temperatures of 10.5 °C (Cianci 1969).
- Upstream migration is reported to begin at temperatures between 5◦C and 10◦C (Loesch 1987), little instream movement occurs below 8◦C or over 18◦C (Collette and KleinMacPhee 2002), and spawning ceases at water temperatures exceeding 27◦C (Kissil 1974).
- Appropriate spawning temperatures broadly fall between 10◦C and 22◦C (Tyus 1974; Pardue 1983; Collette and Klein-MacPhee 2002)
- fish tagged when temperatures were 10.29–22.31◦C (O’Connell & Angermeier, 1997)
- temps measured before the spawning run around 6 C and temps measured during the spawning run 12.8 C-14 C (Durbin et al., 1979).
- spawning begins at 10.5 C (Mullen et al., 1986)
-  Alewives begin spawning when water temperatures reach 10.56 C (Reback et al., 2004). 
-  Both species cease spawning when the water warms to 26.11 C (Reback et al., 2004). 


Temperature preferences during spawning vary across studies, but there is a consensus that optimal temperatures for successful spawning fall within the range of 12 to 16 degrees Celsius [@brown_habitat_2000].
Suitable spawning temperatures broadly span from 12 to 22 degrees Celsius [@tyus_movements_1974; @pardue_habitat_1983; @collette_fishes_2003; @mather_assessing_2012] and during the migration inland, alewives tend to favor offshore locations where bottom temperatures are between 7 and 11 degrees Celsius [@munroe_overview_2000].
Spawning activity significantly diminishes above 27 degrees Celsius [@kissil_spawning_1974; @pardue_habitat_1983; @brown_habitat_2000].
Deviations from the optimal temperature range can significantly impact spawning success and the timing of migration.
Water temperature also plays a critical role in alewife abundance and movement patterns [@legett_daily_2021].

In contrast to earlier models, the new HSI model delineates mean daily temperature preferences with greater accuracy.
While previous models often employed broader temperature categories, the current model introduces finer distinctions.
For instance, the new model identifies a specific range (12 to 16 degrees Celsius) where alewives exhibit peak suitability, providing a more accurate depiction of their thermal requirements for successful spawning.
Moreover, the model highlights an upper mean daily temperature limit (27 degrees Celsius) where suitability drastically decreases, emphasizing the importance of maintaining suitable thermal conditions in spawning habitats.

#### Depth

- 0.15–3 m @pardue_habitat_1983
- spawning habitat were all 0.5m or less (Kosa & Mather, 2001)
- Species of herring from the same cluepid family have been known to spawn majority 0.5-5m and up to 15 m (Haegele & Schweigert, 1985).

In terms of depth preferences, spawning adult alewives are generally known to favor depths ranging from Mean Low Tide (MLT) to 10 meters [@brown_habitat_2000], but recent field observations indicate that a significant proportion of alewives can be found in habitats as shallow as 2 meters [@mather_assessing_2012].
Offshore alewives migrating inland have been documented to favor deeper depths (depth < 100m) [@pardue_habitat_1983; @munroe_overview_2000].

The updated model also offers more detailed depth preferences.
Previous models might have employed generalized depth categories, but the new model introduces distinct depth ranges.
This allows for a more refined assessment of habitat suitability.
For instance, the new model specifies a peak suitability range (2 to 10 meters), reflecting the depth preferences of spawning adult alewives more accurately.
Additionally, it identifies a depth threshold (100 meters) beyond which habitats are unsuitable for spawning.

#### Salinity

Further, documented behavior of alewives challenges the conventional belief that anadromous species exclusively depend on freshwater environments for spawning.
Alewives have been widely observed spawning in freshwater tidal habitats with minimal salinity concentrations, revealing a habitat use in environments with salinity levels below 0.5 psu [@pardue_habitat_1983].
However, they can tolerate salinity levels as high as 8 psu for successful spawning, as documented in the study conducted by @able_alewife_2020. More recently, @brown_habitat_2000 emphasizes an additional heightened preference for habitats with salinity concentrations below 15 psu, while concentrations surpassing 20 psu are deemed unsuitable for spawning adults.
Additionally, field studies have documented that adult alewives engage in spawning activities across a diverse array of estuary habitats with varying salinity levels, including ponds within coastal systems, pond-like regions within coastal rivers and streams, oxbows, eddies, backwaters, stream pools, and flooded swamps [@pardue_habitat_1983; @mullen_species_1986; @collette_fishes_2003; @walsh_early_2005]. Species of herring from the same cluepid family have been known to spawn in a range of salinities from freshwater to 35+ psus (Haegele & Schweigert, 1985).

The new HSI model also refines the depiction of alewife salinity preferences.
Unlike earlier models, which may have had narrow salinity categories, the updated model provides a more nuanced view.
It pinpoints a specific range (0 to 5 psu) where alewives exhibit the highest suitability, aligning closely with empirical data.
Moreover, it designates a clear upper limit (20 psu) where suitability declines significantly, indicating the importance of maintaining lower salinity levels in suitable habitats.

#### Flow Velocity

The new model enhances our understanding of alewife flow velocity preferences.
While previous models might have used less specific flow velocity categories, the updated model introduces distinct ranges.
For example, it highlights a range (0 to 0.3 meters per second) where alewives demonstrate the highest suitability and extends moderate suitability to a broader range (0.3 to 1.5 meters per second), offering a more defined view of their flow velocity requirements.
Additionally, it designates an upper threshold (4.5 meters per second) beyond which habitat would be considered unsuitable, in line with observed behaviors.

#### Substrate

Substrate preferences remain a crucial aspect of spawning habitat for alewives.
Previous models have employed general substrate categories, while the new model emphasizes the significance of diverse substrate types, including soft (e.g. small gravel, sand, silt, detritus) and hard substrates (e.g. cobble, rock, boulders, clam beds), as well as sub-aquatic vegetation (i.e. absence/presence).

### Non-Migratory Juveniles

+----------------------------+--------------------+-------------------------------+
| **Parameter**              | Range              | **Habitat Suitability Value** |
+============================+====================+===============================+
| A. Temperature (°C)        | $0 < t < 8$        | 0.0                           |
|                            |                    |                               |
|                            | $8 <= t < 12$      | 0.5                           |
|                            |                    |                               |
|                            | $12 <= t < 16$     | 1.0                           |
|                            |                    |                               |
|                            | $16 <= t < 22$     | 1.0                           |
|                            |                    |                               |
|                            | $22 <= t < 27$     | 0.5                           |
|                            |                    |                               |
|                            | $27 <= t < 30$     | 0.1                           |
|                            |                    |                               |
|                            | $t > 30$           | 0.0                           |
+----------------------------+--------------------+-------------------------------+
| B. Depth (*meters*)        | $MLT < d < 2$      | 0.0                           |
|                            |                    |                               |
|                            | $2 <= d < 10$      | 0.5                           |
|                            |                    |                               |
|                            | $10 <= d < 20$     | 1.0                           |
|                            |                    |                               |
|                            | $20 <= d < 50$     | 0.5                           |
|                            |                    |                               |
|                            | $50 <= d < 100$    | 0.5                           |
|                            |                    |                               |
|                            | $d > 100$          | 0.5                           |
+----------------------------+--------------------+-------------------------------+
| C. Salinity (*psu*)        | $0 < s < 0.5$      | 1.0                           |
|                            |                    |                               |
|                            | $0.5 <= s < 5.0$   | 1.0                           |
|                            |                    |                               |
|                            | $5.0 <= s < 15.0$  | 1.0                           |
|                            |                    |                               |
|                            | $15.0 <= s < 20.0$ | 0.5                           |
|                            |                    |                               |
|                            | $s > 20$           | 0.0                           |
+----------------------------+--------------------+-------------------------------+
| D. Flow Velocity (*m/s*)   | $0 < v < 0.3$      | 1.0                           |
|                            |                    |                               |
|                            | $0.3 <= v < 1.5$   | 1.0                           |
|                            |                    |                               |
|                            | $1.5 <= v < 3.5$   | 0.5                           |
|                            |                    |                               |
|                            | $3.5 <= v < 4.5$   | 0.3                           |
|                            |                    |                               |
|                            | $v > 5$            | 0.0                           |
+----------------------------+--------------------+-------------------------------+
| E. Substrate               | Hard Substrate     | 0.5                           |
|                            |                    |                               |
|                            | Soft Substrate     | 1.0                           |
|                            |                    |                               |
|                            | Present SAV        | 1.0                           |
|                            |                    |                               |
|                            | Absent SAV         | 0.5                           |
+----------------------------+--------------------+-------------------------------+

: **Table 2.** Model Parameters and Habitat Suitability Values for Non-Migratory Juvenile Alewives

#### Temperature

#### Depth

#### Salinity

#### Flow Velocity

#### Substrate

### Eggs & Larvae

+----------------------------+--------------------+-------------------------------+
| **Parameter**              | Range              | **Habitat Suitability Value** |
+============================+====================+===============================+
| A. Temperature (°C)        | $0 < t < 8$        | 0.0                           |
|                            |                    |                               |
|                            | $8 <= t < 12$      | 0.5                           |
|                            |                    |                               |
|                            | $12 <= t < 16$     | 1.0                           |
|                            |                    |                               |
|                            | $16 <= t < 22$     | 1.0                           |
|                            |                    |                               |
|                            | $22 <= t < 27$     | 0.5                           |
|                            |                    |                               |
|                            | $27 <= t < 30$     | 0.1                           |
|                            |                    |                               |
|                            | $t > 30$           | 0.0                           |
+----------------------------+--------------------+-------------------------------+
| B. Depth (*meters*)        | $MLT < d < 2$      | 0.0                           |
|                            |                    |                               |
|                            | $2 <= d < 10$      | 0.5                           |
|                            |                    |                               |
|                            | $10 <= d < 20$     | 1.0                           |
|                            |                    |                               |
|                            | $20 <= d < 50$     | 0.5                           |
|                            |                    |                               |
|                            | $50 <= d < 100$    | 0.5                           |
|                            |                    |                               |
|                            | $d > 100$          | 0.5                           |
+----------------------------+--------------------+-------------------------------+
| C. Salinity (*psu*)        | $0 < s < 0.5$      | 1.0                           |
|                            |                    |                               |
|                            | $0.5 <= s < 5.0$   | 1.0                           |
|                            |                    |                               |
|                            | $5.0 <= s < 15.0$  | 1.0                           |
|                            |                    |                               |
|                            | $15.0 <= s < 20.0$ | 0.5                           |
|                            |                    |                               |
|                            | $s > 20$           | 0.0                           |
+----------------------------+--------------------+-------------------------------+
| D. Flow Velocity (*m/s*)   | $0 < v < 0.3$      | 1.0                           |
|                            |                    |                               |
|                            | $0.3 <= v < 1.5$   | 1.0                           |
|                            |                    |                               |
|                            | $1.5 <= v < 3.5$   | 0.5                           |
|                            |                    |                               |
|                            | $3.5 <= v < 4.5$   | 0.3                           |
|                            |                    |                               |
|                            | $v > 5$            | 0.0                           |
+----------------------------+--------------------+-------------------------------+
| E. Substrate               | Hard Substrate     | 0.5                           |
|                            |                    |                               |
|                            | Soft Substrate     | 1.0                           |
|                            |                    |                               |
|                            | Present SAV        | 1.0                           |
|                            |                    |                               |
|                            | Absent SAV         | 0.5                           |
+----------------------------+--------------------+-------------------------------+

: **Table 3.** Model Parameters and Habitat Suitability Values for Alewife Larvae and Egg Development Stages

#### Temperature

#### Depth

#### Salinity

#### Flow Velocity

#### Substrate
