# Blueback Herring (*Alosa aestivalis*) {#blueback}

This chapter aims to explore the habitat preferences and life cycle of blueback herring (*Alosa aestivalis*) in the northeastern United States.
Blueback herring have faced significant declines,

This chapter explores the favorable habitat conditions for spawning blueback adults, non-migratory juveniles, as well as eggs and larvae, which are influenced by factors such as suitable spawning habitats, water quality conditions, and availability of appropriate food resources [@lynch_projected_2015].

 blueback herring spawn in higher salinity, faster-moving waters in the lower river (Turner & Limburg, 2016)
 
## Life cycle overview

- Alewives enter the river first, followed by blueback herring 2-3 weeks later (Jessop 2003).
- juveniles may take longer to move into brackish waters (Schmidt et al. 1988).
- Blueback larvae demonstrate the ability to adapt to marine environments by 58 days post-hatch (DiMaggio et al., 2015).

Alewife migration and spawning precedes blueback herring by 2-3 weeks [@fay_alewifeblueback_1983].

## Habitat Requirements

### Spawning Adults

#### Temperature

- move into estuary begins at 14 and ceases at 27 @pardue_habitat_1983

- 16 - 16 klauda et al 1991

- Our results indicate that blueback herring adults require temperatures of at least 16.8"C to spawn. (O'Connell & Angermeier, 1999)

- range 17 - 26 and optimal 20 - 24 @pardue_habitat_1983

- spawning stops at 27 @pardue_habitat_1983

- Our results demonstrate that the spawning temperature that maximized juvenile blueback herring abundance in the Delaware River was 11 °C (tommasi 2015)

- spawning begins at 14 C (Mullen et al., 1986)
-  Alewives begin spawning when water temperatures reach 51 and bluebacks 57 degrees F (Reback et al., 2004). 
-  Both species cease spawning when the water warms to 81°F (Reback et al., 2004). 

#### Depth

- 0.15–3 m @pardue_habitat_1983
- spawning habitat were all 0.5 m or less (Kosa & Mather, 2001)
- Species of herring from the same cluepid family have been known to spawn majority 0.5-5m and up to 15 m (Haegele & Schweigert, 1985).
-  Overall depth preferences for spawning blueback seems similar to alewife and therefore same depth preferences are assumed

#### Salinity

-  spawning begins then or shortly thereafter. Although this species apparently spawns primarily in fresh water, spawning also occurs in brackish ponds at Woods Hole (Nichols and Breder, 1926; Hildebrand, 1963). 

- I  found that the chief spawning grounds in the Delaware River were in tidal water (Chittenden, 1972)
- Species of herring from the same cluepid family have been known to spawn in a range of salinities from freshwater to 35+ psus (Haegele & Schweigert, 1985).
- Alewives have been widely observed spawning in freshwater tidal habitats with minimal salinity concentrations, revealing a habitat use in environments with salinity levels below 0.5 psu [@pardue_habitat_1983].
- Blueback herring in Winnegance Lake and Patten Pond show a preference for high salinity environments for spawning, indicated by their limited residency time in freshwater. The immediate transition of fish from Winnegance Lake to the estuary after spawning suggests a preference for high salinity spawning, with the estuarine environment supporting early egg and larvae development (Payne Wynne et al., 2015). blueback herring seem to be able to tolerate higher salinity levels for spawning activity adn are even known to spawn in areas where freshwater input is extremely minimal 

#### Flow Velocity

-   blueback herring show a preferance for higher velocities than alewives (haro 2004)
- prefer fluvial environments which are higher velocity and not stagnant
- Low velocities (0.0--1.7 m/s) (Walsh et al 2005)
- 0.11 m/s (O'Connell & Angermeier, 1997)
- blueback tend to favor running water and a fairly clean hard bottom, Bourne 1990
- Both species spawn primarily in habitats with little or no current Walsh 2005


#### Substrate

-   Blueback herring do not usually spawn as far upstream as the alewife and selectively choose spawning sites in fast-flowing water over a hard substrate, particularly in shared spawning grounds (Loesch and Lund 1977; Jones et al. 1978; Scott and Scott 1988).

-   blueback tend to favor running water and a fairly clean hard bottom, bourne 1990

- prefer hard substrate (Loesch and Lund 1977)

### Non-Migratory Juveniles

#### Temperature

- higher preference than alewife juveniles

- supported in observations where Eel River had a mean temperature of 23.1°C, while the Herring River (Bourne) had temperatures with a mean of 25.1°C (Ames & Lichter, 2013).

#### Depth

-   Juvenile Blueback herring in Potomac River, Virginia abundant in 4.6 m(Mullen et al., 1986)

#### Salinity

Bluebacks:

Bluebacks exhibit high survival rates when transferred between certain salinities, particularly from 3‰, 15‰, and 30‰ into 3‰ salinity.
The high survival rates indicate that Bluebacks are well-adapted and can thrive under a range of salinity conditions within the specified experimental scenarios.
While the information does not explicitly state a preference for specific salinities, the high survival rates suggest that Bluebacks may have a relatively broad salinity tolerance in the studied range.(DiMaggio et al., 2015)

- blueback herring is highly salinity tolerant early in life (28 psu)  (Chittenden, 1972)
- herring eggs and larvae developing in abundance in sea-water with healthy and active larvae (Ford, 1929)

#### Flow Velocity
- Previous optimal velocities for larvae and egg development were observed from 0 to 0.3 m/s [@pardue_habitat_1983].


#### Substrate
-   blueback tend to favor running water and a fairly clean hard bottom, bourne 1990

### Eggs and Larvae

#### Temperature

-  blueback herring early egg stages were positively related to water temperature (14-22°C). (O'Connell & Angermeier, 1999)
- Blueback herring eggs have been found in  water temperatures ranging from 7 to 14°C in the upper Chesapeake Bay, with most being collected at  14°C (Dove1 1971).
- Temperatures observed in our study were always below those known to impair hatching success (32.9 to 36.1°C) or cause larval deformities (34°C). (O'Connell & Angermeier, 1999)
- eggs recorded at 20-24 C (Mullen et al., 1986)
- 19 C 0-5% deformities, 20 0-24% deformities, Complete larval deformities in eggs exposed to 34 C (Koo and Johnston 1978)
- 11.48C to 23.08C, 10.98C to 20.88C walsh 2005
- Larvae were not found in the canal oroxbow  until  late  April  and  were  never  abundantat water temperatures below 148C (walsh 2005).
- peak densities were positively associated with peaks in water temperature (within the range of 4-19 C) (O’Connell & Angermeier, 1999).


#### Depth

-  In Lake Ontario, early post-hatch larvae were most abundant in shallow areas less than 3m in depth, with larger larvae progressively occupying deeper habitat (Dunstall 1984).
- Larval Alosa in Nova Scotian fmgs rivers inhabite-i-waters that were relatively shallow (<2 m) (Mullen et al., 1986)

#### Salinity

- Bluebacks:

The mean survival rates for Bluebacks consistently increase with higher salinities.
The highest mean survival rate for Bluebacks is observed at 30‰ salinity (95.3%).
This pattern indicates that Bluebacks may exhibit a preference for higher salinity conditions, as indicated by their higher survival rates at 30‰ compared to lower salinities. (DiMaggio et al., 2015)

- highly tolerant of salinity changes (Mullen et al., 1986)

-  Pacific herring eggs are tolerant to salinities in the range of 3-33% (Haegele & Schweigert, 1985).
- blueback herring embryos displayed a wide salinity tolerance throughout the range. Embryos of both species exhibited high survival in tidal salinity exposures. Survival of acutely-transferred alewife and blueback herring larvae decreased with increasing salinity (>20 g/L)(DiMaggio et al., 2016).

#### Flow Velocity

- lower temperatures and peaks in river flow negatively impacted early life stages (O’Connell & Angermeier, 1999)

#### Substrate

-  thought to provide spawning and nursery habitat for anadromous and resident fishes (Miller et al 2006); however, in the case of alewives, larval catch was inversely related to vegetation density. larvae were most frequently found in areas with less than 10 percent vegetation density and were never found in areas where vegetation density exceeded 30 percent (Ingel, 2013).

## Habitat suitability models

### Spawning Adults

+----------------------------+--------------------+-------------------------------+
| **Parameter**              | Range              | **Habitat Suitability Value** |
+============================+====================+===============================+
| A. Temperature (°C)        | $0 < t < 8$        | 0.0                           |
|                            |                    |                               |
|                            | $8 <= t < 12$      | 0.5                           |
|                            |                    |                               |
|                            | $12 <= t < 16$     | 1.0                           |
|                            |                    |                               |
|                            | $16 <= t < 22$     | 1.0                           |
|                            |                    |                               |
|                            | $22 <= t < 27$     | 0.5                           |
|                            |                    |                               |
|                            | $27 <= t < 30$     | 0.1                           |
|                            |                    |                               |
|                            | $t > 30$           | 0.0                           |
+----------------------------+--------------------+-------------------------------+
| B. Depth (*meters*)        | $MLT < d < 2$      | 0.0                           |
|                            |                    |                               |
|                            | $2 <= d < 10$      | 0.5                           |
|                            |                    |                               |
|                            | $10 <= d < 20$     | 1.0                           |
|                            |                    |                               |
|                            | $20 <= d < 50$     | 0.5                           |
|                            |                    |                               |
|                            | $50 <= d < 100$    | 0.5                           |
|                            |                    |                               |
|                            | $d > 100$          | 0.5                           |
+----------------------------+--------------------+-------------------------------+
| C. Salinity (*psu*)        | $0 < s < 0.5$      | 1.0                           |
|                            |                    |                               |
|                            | $0.5 <= s < 5.0$   | 1.0                           |
|                            |                    |                               |
|                            | $5.0 <= s < 15.0$  | 1.0                           |
|                            |                    |                               |
|                            | $15.0 <= s < 20.0$ | 0.5                           |
|                            |                    |                               |
|                            | $s > 20$           | 0.0                           |
+----------------------------+--------------------+-------------------------------+
| D. Flow Velocity (*m/s*)   | $0 < v < 0.3$      | 1.0                           |
|                            |                    |                               |
|                            | $0.3 <= v < 1.5$   | 1.0                           |
|                            |                    |                               |
|                            | $1.5 <= v < 3.5$   | 0.5                           |
|                            |                    |                               |
|                            | $3.5 <= v < 4.5$   | 0.3                           |
|                            |                    |                               |
|                            | $v > 5$            | 0.0                           |
+----------------------------+--------------------+-------------------------------+
| E. Substrate               | Hard Substrate     | 0.5                           |
|                            |                    |                               |
|                            | Soft Substrate     | 1.0                           |
|                            |                    |                               |
|                            | Present SAV        | 1.0                           |
|                            |                    |                               |
|                            | Absent SAV         | 0.5                           |
+----------------------------+--------------------+-------------------------------+

: **Table 1.** Model Parameters and Habitat Suitability Values for Spawning Adult Blueback Herring.

#### Temperature

#### Depth

#### Salinity

#### Flow Velocity

#### Substrate

### Non-Migratory Juveniles

+----------------------------+--------------------+-------------------------------+
| **Parameter**              | Range              | **Habitat Suitability Value** |
+============================+====================+===============================+
| A. Temperature (°C)        | $0 < t < 8$        | 0.0                           |
|                            |                    |                               |
|                            | $8 <= t < 12$      | 0.5                           |
|                            |                    |                               |
|                            | $12 <= t < 16$     | 1.0                           |
|                            |                    |                               |
|                            | $16 <= t < 22$     | 1.0                           |
|                            |                    |                               |
|                            | $22 <= t < 27$     | 0.5                           |
|                            |                    |                               |
|                            | $27 <= t < 30$     | 0.1                           |
|                            |                    |                               |
|                            | $t > 30$           | 0.0                           |
+----------------------------+--------------------+-------------------------------+
| B. Depth (*meters*)        | $MLT < d < 2$      | 0.0                           |
|                            |                    |                               |
|                            | $2 <= d < 10$      | 0.5                           |
|                            |                    |                               |
|                            | $10 <= d < 20$     | 1.0                           |
|                            |                    |                               |
|                            | $20 <= d < 50$     | 0.5                           |
|                            |                    |                               |
|                            | $50 <= d < 100$    | 0.5                           |
|                            |                    |                               |
|                            | $d > 100$          | 0.5                           |
+----------------------------+--------------------+-------------------------------+
| C. Salinity (*psu*)        | $0 < s < 0.5$      | 1.0                           |
|                            |                    |                               |
|                            | $0.5 <= s < 5.0$   | 1.0                           |
|                            |                    |                               |
|                            | $5.0 <= s < 15.0$  | 1.0                           |
|                            |                    |                               |
|                            | $15.0 <= s < 20.0$ | 0.5                           |
|                            |                    |                               |
|                            | $s > 20$           | 0.0                           |
+----------------------------+--------------------+-------------------------------+
| D. Flow Velocity (*m/s*)   | $0 < v < 0.3$      | 1.0                           |
|                            |                    |                               |
|                            | $0.3 <= v < 1.5$   | 1.0                           |
|                            |                    |                               |
|                            | $1.5 <= v < 3.5$   | 0.5                           |
|                            |                    |                               |
|                            | $3.5 <= v < 4.5$   | 0.3                           |
|                            |                    |                               |
|                            | $v > 5$            | 0.0                           |
+----------------------------+--------------------+-------------------------------+
| E. Substrate               | Hard Substrate     | 0.5                           |
|                            |                    |                               |
|                            | Soft Substrate     | 1.0                           |
|                            |                    |                               |
|                            | Present SAV        | 1.0                           |
|                            |                    |                               |
|                            | Absent SAV         | 0.5                           |
+----------------------------+--------------------+-------------------------------+

: **Table 2.** Model Parameters and Habitat Suitability Values for Non-Migratory Juvenile Blueback Herring.

#### Temperature

#### Depth

#### Salinity

#### Flow Velocity

#### Substrate

Previous studies have presented conflicting information regarding the substrate preferences of spawning adult blueback herring, likely stemming from the generalization of alewives with blueback herring as river herring.
Adult blueback herring spawn over both soft and hard substrates [@pardue_habitat_1983; @oconnell_spawning_1997; @brown_habitat_2000].

Aside from their demonstrated dependence on soft substrates, spawning adult alewives also exhibit a pronounced inclination toward habitats containing sub-aquatic vegetation [@killgore_distribution_1988; @laney_relationship_1997].
Comprehending and defining these substrate preferences is crucial to effectively manage and conserve the appropriate spawning habitats for alewives.

### Larvae

+----------------------------+--------------------+-------------------------------+
| **Parameter**              | Range              | **Habitat Suitability Value** |
+============================+====================+===============================+
| A. Temperature (°C)        | $0 < t < 8$        | 0.0                           |
|                            |                    |                               |
|                            | $8 <= t < 12$      | 0.5                           |
|                            |                    |                               |
|                            | $12 <= t < 16$     | 1.0                           |
|                            |                    |                               |
|                            | $16 <= t < 22$     | 1.0                           |
|                            |                    |                               |
|                            | $22 <= t < 27$     | 0.5                           |
|                            |                    |                               |
|                            | $27 <= t < 30$     | 0.1                           |
|                            |                    |                               |
|                            | $t > 30$           | 0.0                           |
+----------------------------+--------------------+-------------------------------+
| B. Depth (*meters*)        | $MLT < d < 2$      | 0.0                           |
|                            |                    |                               |
|                            | $2 <= d < 10$      | 0.5                           |
|                            |                    |                               |
|                            | $10 <= d < 20$     | 1.0                           |
|                            |                    |                               |
|                            | $20 <= d < 50$     | 0.5                           |
|                            |                    |                               |
|                            | $50 <= d < 100$    | 0.5                           |
|                            |                    |                               |
|                            | $d > 100$          | 0.5                           |
+----------------------------+--------------------+-------------------------------+
| C. Salinity (*psu*)        | $0 < s < 0.5$      | 1.0                           |
|                            |                    |                               |
|                            | $0.5 <= s < 5.0$   | 1.0                           |
|                            |                    |                               |
|                            | $5.0 <= s < 15.0$  | 1.0                           |
|                            |                    |                               |
|                            | $15.0 <= s < 20.0$ | 0.5                           |
|                            |                    |                               |
|                            | $s > 20$           | 0.0                           |
+----------------------------+--------------------+-------------------------------+
| D. Flow Velocity (*m/s*)   | $0 < v < 0.3$      | 1.0                           |
|                            |                    |                               |
|                            | $0.3 <= v < 1.5$   | 1.0                           |
|                            |                    |                               |
|                            | $1.5 <= v < 3.5$   | 0.5                           |
|                            |                    |                               |
|                            | $3.5 <= v < 4.5$   | 0.3                           |
|                            |                    |                               |
|                            | $v > 5$            | 0.0                           |
+----------------------------+--------------------+-------------------------------+
| E. Substrate               | Hard Substrate     | 0.5                           |
|                            |                    |                               |
|                            | Soft Substrate     | 1.0                           |
|                            |                    |                               |
|                            | Present SAV        | 1.0                           |
|                            |                    |                               |
|                            | Absent SAV         | 0.5                           |
+----------------------------+--------------------+-------------------------------+

: **Table 3.** Model Parameters and Habitat Suitability Values for Blueback Herring Larvae Stage.

#### Temperature

#### Depth

#### Salinity

#### Flow Velocity

#### Substrate
