# Discussion


## Strengths

## Limitations

  - regional 
  - accuracy based on current knowledge
  - prediction power
  
- Compare to similar models (Pardue & Brown)

other factors impacting habitat health that could be added in the future
- nitrogen
- dissolved oxygen
- PH levels
"Blueback eggs and larvae to pulses of acidified water 
(pH 5.5 to 5.6) was reported to increase their 
mortality rate substantially (Klauda, 1987; see also 
Byrne, 1988). The pH of many Cape and Island soils is 
roughly in tnis range, and the ability of these soils 
to neutralize additional acidic inputs is limited. Bourne 1990)

## Implications for River Herring

## Management Implications

- Discussion of whether the model is communicated effectively for accurate and easy application in other project locations. 
- Are the assumptions and limitations staated clearly
- Is the model clear? (are the breakpoints presented in a way that is clear and understandable)
- Are the results understandable? What do the results mean? 

  - Previewing the role of the discussion and summary chapters in interpreting findings.
- different life stages have drastically different preferences and therefore independent models should be utilized to accommodate the different resource needs at different life stages for river herring. River herring species should be careful generalizing alewife and blueback herring species together as species exhibit different habitat preferences.
   - Emphasizing the contribution of the study to advancing river herring management practices.
Utlizing multiple models that reflect the conditions for optimal development and spawning of alewives and blueback herring can identify management weaknesses at different life stages. For example, ____ found that although habitat resources were sufficient for juveniles, habita for egg and larvae developement was lacking.